Add default value for data version in CLI
odk-x/suitcase pull request #49
Opened 2021-03-18 10:49 UTC by Shubhamr837

Default dataVersion is set to 2 for the CLI .
should fix https://github.com/odk-x/tool-suite-X/issues/197

2021-03-18 21:27 UTC, wbrunette commented
runtests

2021-03-19 06:29 UTC, linl33 requested changes
Thanks for sending in the pull request!

2021-03-19 06:29 UTC, linl33 commented on src/main/java/org/opendatakit/suitcase/ui/SuitcaseCLI.java
> +        version = line.getOptionValue(DATA_VERSION_OPT);
You could supply the default value directly to `getOptionValue` see an example on https://github.com/odk-x/suitcase/pull/49/files#diff-9851d999d0c7a8e7293d5cbb8cf98908b843b59ce1485c203537e99dbbcb9684L325

2021-03-19 06:29 UTC, linl33 commented on src/main/java/org/opendatakit/suitcase/ui/SuitcaseCLI.java
> +  private String default_data_version = "2";
Please make this a static final constant.

2021-03-19 06:29 UTC, linl33 commented
runtests

2021-03-19 11:09 UTC, Shubhamr837 commented
Thanks for the suggestions . I have implemented the changes .
Please Review If any other changes are required .

2021-03-19 13:09 UTC, linl33 commented
runtests

2021-03-19 16:48 UTC, linl33 approved these changes

2021-03-19 16:49 UTC, merged